api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false

middlewares:
  cors-headers:
    headers:
      accessControlAllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      accessControlAllowHeaders:
        - Origin
        - Content-Type
        - Accept
        - Authorization
        - Cookie
      accessControlAllowCredentials: true
      accessControlAllowOriginList:
        - "http://localhost:5173"



